run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unparam
    - unconvert
    - goconst
    - gocyclo
    - revive
    - gosec
    - nilerr
    - stylecheck
    - prealloc

linters-settings:
  gocyclo:
    min-complexity: 15
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: error-return
        severity: warning
        disabled: false
      - name: error-naming
        severity: warning
        disabled: false
      - name: if-return
        severity: warning
        disabled: false
  
  gosec:
    excludes:
      - G104 # Audit errors not checked
      - G204 # Subprocess launched with variable

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
    
    # Exclude known linters from partially hard-vendored code
    - path: vendor/
      linters:
        - stylecheck
        - gosec
        - gocritic
