apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ans-system

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: ans-resolver
  app.kubernetes.io/part-of: ans
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ans-resolution-server
    newName: ghcr.io/route-ans/route-ans
    newTag: latest

configMapGenerator:
  - name: ans-resolver-config
    behavior: merge
    literals:
      - LOG_LEVEL=info

secretGenerator:
  - name: ans-resolver-secrets
    type: Opaque
    literals:
      - redis.password=changeme
